### ISSUE TITLE
Stretch 1: Tracking fish

### ISSUE THREAD

**Issue by caseywalker** [caseywalker/ASSIGNMENT-Bear-Watcher#9]
- [ ] As a user, I should be able to click something on each bear to indicate it has just tried to catch a fish.
- [ ] As a user, I should be able to click something on each bear to indicate it has just successfully caught a fish.
- [ ] As a user, looking at a bear card I should see time stamps and statuses for each time a bear caught a fish or attempted to catch a fish
- [ ] As a user, looking at a bear card, I should see a total number of fish caught tally.
